spring:
  datasource:
    password: lWmjOp97q6rlXmH0zt5nGm501UUjsJoN
    url: jdbc:postgresql://dpg-cu8gjel6l47c738hs450-a.singapore-postgres.render.com/internhubdb
    username: dung
    driver-class-name: org.postgresql.Driver