spring:
  datasource:
    password: CHGqLAP2c6fD1Jdk8fKl8PSfZQ4HssKU
    url: jdbc:postgresql://dpg-cutujrl6l47c73a9hegg-a.singapore-postgres.render.com:5432/internhubdb_wpk4
    username: kalocs
    driver-class-name: org.postgresql.Driver