spring.application.name=Internhub
app-version=0.0.1
logging.level.root=info
server.port=${SERVER_PORT:8082}
server.servlet.context-path=${SERVER_SERVLET_CONTEXT_PATH:/api}
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
server.compression.min-response-size=1KB
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

internhub.app.jwtSecret=${INTERNHUB_JWTSECRET:internhubjwtsecret}
internhub.app.jwtExpirationMs=${INTERNHUB_EXPIRATIONMS:86400000}
internhub.app.authorizedRedirectUris=${INTERNHUB_FE_URL:http://localhost:5173}/oauth2/redirect
internhub.app.front-end-url=${INTERNHUB_FE_URL:http://localhost:5173}
internhub.app.backend-url=${INTERNHUB_BE_URL:http://localhost:8082}
internhub.app.backend-server-url=${INTERNHUB_BE_SERVER_URL:http://localhost:8082/api}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:your-client-id}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:your-client-secret}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/oauth2/callback/{registrationId}


cloudinary.url=cloudinary://${CLOUDINARY_API_KEY}:${CLOUDINARY_API_SECRET}@${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}

vnpay.vnp-hash-secret=${VNP_HASH_SECRET}
vnpay.vnp-tmn-code=${VNP_TMN_CODE}
