spring:
  datasource:
    password: uWgDB4JqX2XTxkdfAOo4ZlmHX1eNy71D
    url: jdbc:postgresql://dpg-cvn8io49c44c73dkc68g-a.singapore-postgres.render.com:5432/internhub_6g0h
    username: kalocs
    driver-class-name: org.postgresql.Driver